FROM --platform=linux/amd64 ghcr.io/foundry-rs/foundry

# 設定工作目錄並複製專案
WORKDIR /app
COPY . .

# 安裝依賴與編譯
RUN forge build
RUN forge test

# 開放 Anvil 默認端口
EXPOSE 8545

# 啟動 Anvil 並執行腳本
ENTRYPOINT ["sh", "-c", "anvil & sleep 3 && forge script script/deploy.s.sol --rpc-url http://127.0.0.1:8545 --broadcast"]